# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: todo-app-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - todo_db:/var/lib/mysql

  adminer:
    container_name: todo-app-adminer
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  todo_db:
