# Use root/example as user/password credentials
version: '3.5'

services:

  db:
    image: mysql
    container_name: todo-app-db
    networks:
      - todo-app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - todo_db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: todo-app-adminer
    networks:
      - todo-app
    restart: always
    ports:
      - 8000:8080

volumes:
  todo_db:

networks:
  todo-app:
    name: todo-network
